#!/usr/bin/env bash

# A Bash script that displays the time for 12 hours and 59 minutes:
# - Display hours from 0 to 12
# - Display minutes from 1 to 59 for each hour

hour=0
while [ $hour -le 12 ]; do
    echo "hour: $hour"
    minutes=1
    while [ $minutes -le 59 ]; do
        echo "  $minutes"
        ((minutes++))
    done
    ((hour++))
done	
