#!/usr/bin/env bash
# Gracefully reloads Gunicorn by sending the HUP signal to its process.

# Find Gunicorn processes and send the HUP signal
if pgrep gunicorn > /dev/null; then
    pgrep gunicorn | xargs kill -HUP
    echo "Gunicorn gracefully reloaded."
else
    echo "Gunicorn process not found."
fi
